msm8226-common: hal3on1: Fix possible Buffer Overflow or Wrong Size in Update.
--------- beginning of crash
09-05 14:19:00.704 10599 10637 E AndroidRuntime: FATAL EXCEPTION: CameraX-core_camera_0
09-05 14:19:00.704 10599 10637 E AndroidRuntime: Process: app.grapheneos.camera, PID: 10599
09-05 14:19:00.704 10599 10637 E AndroidRuntime: java.lang.AssertionError: java.lang.reflect.InvocationTargetException
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at android.hardware.camera2.marshal.impl.MarshalQueryableRange$MarshalerRange.unmarshal(MarshalQueryableRange.java:95)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at android.hardware.camera2.marshal.impl.MarshalQueryableRange$MarshalerRange.unmarshal(MarshalQueryableRange.java:37)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at android.hardware.camera2.marshal.impl.MarshalQueryableArray$MarshalerArray.unmarshal(MarshalQueryableArray.java:157)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at android.hardware.camera2.impl.CameraMetadataNative.getBase(CameraMetadataNative.java:637)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at android.hardware.camera2.impl.CameraMetadataNative.get(CameraMetadataNative.java:492)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at android.hardware.camera2.impl.CameraMetadataNative.get(CameraMetadataNative.java:461)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at android.hardware.camera2.CameraCharacteristics.get(CameraCharacteristics.java:306)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at r.b.a(Unknown Source:38)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at androidx.camera.camera2.internal.compat.quirk.AeFpsRangeLegacyQuirk.<init>(Unknown Source:5)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at x.c.v(Unknown Source:54)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at q.B.<init>(Unknown Source:42)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at q.m.b(Unknown Source:14)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at q.m.a(Unknown Source:10)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at K.h.e(Unknown Source:55)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at x.s.run(Unknown Source:180)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at java.lang.Thread.run(Thread.java:1119)
09-05 14:19:00.704 10599 10637 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at java.lang.reflect.Constructor.newInstance0(Native Method)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at android.hardware.camera2.marshal.impl.MarshalQueryableRange$MarshalerRange.unmarshal(MarshalQueryableRange.java:87)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	... 17 more
09-05 14:19:00.704 10599 10637 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: lower must be less than or equal to upper
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	at android.util.Range.<init>(Range.java:62)
09-05 14:19:00.704 10599 10637 E AndroidRuntime:	... 20 more

--Diagnostic and fix provided by a freely available AI tool. Use with caution--
AeFpsRangeLegacyQuirk queries CameraCharacteristics.CONTROL_AE_AVAILABLE_TARGET_FPS_RANGES. During the unmarshalling of the metadata byte array into a Range<Integer> object via reflection, Android throws$
        java.lang.IllegalArgumentException: lower must be less than or equal to upper
The underlying camera HAL/driver is reporting an invalid FPS range where the lower boundary is strictly greater than the upper boundary (e.g., [30, 15]).
CameraX assumes system-provided metadata complies with the Android SDK requirement (lower <= upper) and does not catch IllegalArgumentException during quirk initialization.
The HAL must publish valid CONTROL_AE_AVAILABLE_TARGET_FPS_RANGES values where lower <= upper.